### ISSUE TITLE
Let's plan #1

### ISSUE THREAD

**Issue by jefflembeck** [dimsumjs/Seattle#1]
@TheAlphaNerd You mentioned you'd be in town before Cascadia! Which days?

/cc @marcysutton @KatieK2

**Comment by MylesBorins** [comment]
I get in on the third. Heading to Cascadia on the 7th

**Comment by jefflembeck** [comment]
Also who else wants in on this?

**Comment by marcysutton** [comment]
_Raises hand_

I will be working during the week but I'd love to join!

**Comment by shenoa** [comment]
Count me in!

**Comment by KatieK2** [comment]
Me!

**Comment by alexlande** [comment]
Oh hey y'all!

**Comment by MylesBorins** [comment]
Ok, So I'm thinking Sunday the 5th for noms. Thoughts?

**Comment by KatieK2** [comment]
I am busy (soooo busy) but y'all should go and have an awesome time! I can recommend : O'Asian http://www.oasiankitchen.com/dimsum.htm in downtown for a large group. For a smaller group, try The Purple Dot http://www.purpledotseattle.com/ in the International District.

**Comment by jefflembeck** [comment]
I'm trying to figure out if I'll be in town on the 5th or not :)

I'll definitely be around on the 6th if we want to grab something then as well.

**Comment by marcysutton** [comment]
I'll go! My last day of vacation before starting a new job.

**Comment by MylesBorins** [comment]
Ok... so I'm calling it

O'Asian at 1pm on Sunday. Time is flexible, so is place.

I'm updating the README, please let me know if you can make it!

**Comment by shenoa** [comment]
Sorry, but I can't make that time. I'm bummed! Have fun. 

Shenoa

**Comment by MylesBorins** [comment]
when could you make it? I can reschedule... I have the power and technology :D :D :D

**Comment by shenoa** [comment]
I have a last minute out of town friend staying with us, so it's probably better I bow out. Thanks for asking though, you gave me warm fuzzies. 

Shenoa

**Comment by MylesBorins** [comment]
:smile: 
will we have a chance to meet at cascadia?

**Comment by shenoa** [comment]
I wish! I am cash poor this year, investing both time and money into a new secret (for now) thing. :)

Hype hype hype!

Shenoa

**Comment by daviddias** [comment]
OHAI! :D Apparently I'm in Seattle too, can I come? :D

**Comment by MylesBorins** [comment]
COME ONE.. COME ALL� especially you :P

**Comment by pixelass** [comment]
So since I'm already in  Seattle I might join in

**Comment by jefflembeck** [comment]
I'm out. Gotta get in some family time before bailing for the week. Have a
great time, everybody!

**Comment by pixelass** [comment]
So are there still people going?

**Comment by MylesBorins** [comment]
Most definitely!

I am going with my partner. I know of at least 4 others coming.

See you there!

**Comment by jefflembeck** [comment]
#1 happened

**Comment by daviddias** [comment]
Hi dimsum friends! We are hosting an IPFS meetup this next Thursday and I am looking in ways to reach out to the Seattle community and make sure I'm able to invite everyone. Any suggestions where I should broadcast this info?

Here is a link with all the info: http://attending.io/events/ipfs-seattle-july-2015

Thank you :)
