### ISSUE TITLE
January

### ISSUE THREAD

**Issue by jefflembeck** [dimsumjs/Seattle#10]
1/19
Noon
O'asian!

Let's do this!

**Comment by jefflembeck** [comment]
Holy butts this is next friggin week

**Comment by toddself** [comment]
bah!  i am in nyc!

**Comment by LetMyPeopleCode** [comment]
I have a thing in Bellevue later that day, so I'm WFH out in the
hinterlands at lunch time on the 19th.

**Comment by jefflembeck** [comment]
Omg. I had an appt today and spaced this. I'm so sorry if anybody showed. :(

**Comment by LetMyPeopleCode** [comment]
Should probably close this issue.
