### ISSUE TITLE
February!

### ISSUE THREAD

**Issue by KatieK2** [dimsumjs/Seattle#11]
2/16
Noon
O'asian!

I'll be there! Don't let me dim-sum alone! 🍽

**Comment by MylesBorins** [comment]
SO JELLLL

**Comment by KatieK2** [comment]
@TheAlphaNerd You have nearly a week to figure out how to get here.

**Comment by marcysutton** [comment]
I should be able to make it.

**Comment by toddself** [comment]
I am in Hawaii! Will miss y'all.

**Comment by noam-c** [comment]
Hello! I've never been to this before but it seems like a fun time! I _just_ found out I'll be available, but that's pretty last minute. Could I join in today? If not, I'll definitely catch you all next month. :)

**Comment by marcysutton** [comment]
@noam-c join us!

**Comment by noam-c** [comment]
Great! I'll see you all there. :)

**Comment by jefflembeck** [comment]
Holy cow, another dr. appt. :(

I'm sorry all. Have a great time!

**Comment by KatieK2** [comment]
Bummer. Looks like O'Asian is closed. I'm hanging out front - in a grey hoodie - to find a new place.
