### ISSUE TITLE
New Location Required

### ISSUE THREAD

**Issue by KatieK2** [dimsumjs/Seattle#12]
O’Asian is closed; possibly permanently. I work in the international district, so there's lots of dim sum nearby. I propose the Purple Dot Cafe (https://www.yelp.com/biz/purple-dot-cafe-seattle-2); I have tested the honey walnut shrimp and found them tasty indeed.

**Comment by jefflembeck** [comment]
I am a fan of any place, for sure - even though I miss this a lot (consistent appts on Tuesdays :( ). Purple Dot works for me!

**Comment by jonmadison** [comment]
@KatieK2  you know i love purple dot. :) Harbor City is usually _packed_ at lunch but it's amazing. So i suggest whenever we decide to shift the meeting to 12:30 or 1 sometimes

**Comment by LetMyPeopleCode** [comment]
Purple Dot sounds okay. Hear it's packed late night. What's the lunch crowd
like?

**Comment by toddself** [comment]
I am totally happy with Purple Dot & a new time as well!
