### ISSUE TITLE
March (New Location)

### ISSUE THREAD

**Issue by KatieK2** [dimsumjs/Seattle#13]
3/15
Noon
Purple Dot Cafe (515 Maynard Ave S, Seattle, WA 98104) in the International District

I'm tentative. Sound off if you're able to make it!

**Comment by LetMyPeopleCode** [comment]
I'm WFH in Everett on 3/15.

**Comment by toddself** [comment]
I am down for this!

**Comment by kopasetik** [comment]
I'm in! :smile:

**Comment by KatieK2** [comment]
I'm not gonna make it this month. Y'all have fun! :D

**Comment by kopasetik** [comment]
I'm here. Anyone else?

**Comment by kopasetik** [comment]
If nobody else shows by 12:10, I'm headed to Uwajimayya.

**Comment by toddself** [comment]
Thought we moved to 1?

**Comment by KatieK2** [comment]
Sorry - I kept it at noon b/c the Purple Dot tends to not been too crowded, and I've known some folks need an earlier lunch.
