### ISSUE TITLE
April 19th

### ISSUE THREAD

**Issue by jefflembeck** [dimsumjs/Seattle#16]
Purple Dot
Noon

Let's do it.

**Comment by toddself** [comment]
🔜🆒

**Comment by johana-star** [comment]
:exclamation: :grinning:

**Comment by LetMyPeopleCode** [comment]
On my calendar!

**Comment by jonmadison** [comment]
Ditto--Greg wanna lyft? I'm in Arizona...

---Sent from Boxer | http://getboxer.com

On March 29, 2016 at 12:10:05 PM PDT, Jeff Lembeck notifications@github.com wrote:Purple Dot Noon  Let's do it.  —You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by LetMyPeopleCode** [comment]
Yeah. I'll be in Obidos by then.

**Comment by KatieK2** [comment]
I'll be there.

**Comment by jonmadison** [comment]
i'll be at WebDevCon -- but thinking i may be able to break free for lunch...

**Comment by jonmadison** [comment]
ah yes this is tomorrow not wednesday! unfortunately i have a class until 1pm.

**Comment by jefflembeck** [comment]
LET'S DO THIS

**Comment by toddself** [comment]
💯‼️

So many dumplings

**Comment by LetMyPeopleCode** [comment]
Anyone else commuting from around South lake union and wanna split an uber?

**Comment by johana-star** [comment]
I'm feeling a little under the weather, so I'm going to bow out on this one. 🙁 I hope there's another dimsum.js soon.

**Comment by LetMyPeopleCode** [comment]
Unfortunately, I am suffering from metatarsalgia (pain in the ball of the
foot under the big toe) and am trying to minimize walking today after
getting overconfident yesterday ("my foot feels so much better, I think
I'll get off the bus a stop early and enjoy the sunshine with a little
walk...").
- G

On Tue, Apr 19, 2016 at 10:48 AM, Strand McCutchen <notifications@github.com

**Comment by toddself** [comment]
If anyone wants a ride from the Ballard area I'm leaving in about 25-30 minutes!

**Comment by jefflembeck** [comment]
Running late by 5-10. Be there real quick like

**Comment by MylesBorins** [comment]
Maybe y'all could do this again some day
