### ISSUE TITLE
10/20

### ISSUE THREAD

**Issue by jonmadison** [dimsumjs/Seattle#17]
10/20 is next? is this still a thing? can this still be a thing?

**Comment by jonmadison** [comment]
also, Harbor City is good

**Comment by LetMyPeopleCode** [comment]
I'm rice, soy, and wheat free right now, but I can often find something.

**Comment by toddself** [comment]
This definitely needs to be a thing again.  It's been months!

On Mon, Sep 26, 2016, at 15:05, jon madison wrote:

> also, Harbor City is good
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:
1. https://github.com/dimsumjs/Seattle/issues/17#issuecomment-249711685

**Comment by MylesBorins** [comment]
memories
