### ISSUE TITLE
#2?

### ISSUE THREAD

**Issue by jefflembeck** [dimsumjs/Seattle#2]
Let's do something in early August?

/cc @marcysutton @katiek2 @alexlande @shenoa @ possibly anybody else I missed?

Add people, let's do this. Maybe this time I'll be able to make it :+1:

**Comment by toddself** [comment]
I am in

**Comment by KatieK2** [comment]
August? Yes, August is looking _mostly_ good. 

Do we want weekday or weekend?

**Comment by alexlande** [comment]
I missed last time but am definitely up for this, sign me up for whenever!

**Comment by jefflembeck** [comment]
Do we want to do O'asia again? Sounds like it was a good experience and they offer both weekdays and weekends.

Weekdays tend to be a little easier on me.

**Comment by shenoa** [comment]
I'm down! I'll second both weekdays and O'asia.

**Comment by toddself** [comment]
Weekdays and I know nothing about Seattle Dim Sum places so I'll believe in the hive-mind here!

Do we have a tentative date?  Weekdays are a total go!

**Comment by KatieK2** [comment]
Ok - let's do O'Asian (http://www.oasiankitchen.com/dimsum.htm) next week.

I'm free on Tuesday, Thursday and Friday. Y'all?

**Comment by toddself** [comment]
Any of those days work for me, although Tuesday and Thursday are best.

**Comment by jefflembeck** [comment]
Tuesday works great for me!

**Comment by shenoa** [comment]
Tuesday sounds good to me too.

**Comment by KatieK2** [comment]
Tuesday for lunchtime it is. 11:45? Anyone else?

**Comment by alexlande** [comment]
Sorry y'all, not going to be able to make this one. Next time, I swear!

**Comment by jonmadison** [comment]
oh so 11:45 tomorrow? i have another meeting but gonna try and switch up

**Comment by KatieK2** [comment]
:D :D :D

**Comment by jonmadison** [comment]
See you there. May be a tiny bit late

**Comment by toddself** [comment]
I am a little early waiting just inside.

**Comment by jefflembeck** [comment]
Woohoo. Today was A++.
