### ISSUE TITLE
#3

### ISSUE THREAD

**Issue by jefflembeck** [dimsumjs/Seattle#3]
LET US START PLANNING SEPTEMBER

**Comment by KatieK2** [comment]
Hoping @marcysutton @alexlande can make it this time.

Please tell us your preferences - lunch or dinner? What days of the week work for you? Do you hate downtown and / or dimsum?

**Comment by alexlande** [comment]
I swear I'll show up this time no matter where or when it is :tada:

**Comment by LetMyPeopleCode** [comment]
Just found out about this from Carter's tweet. Is this an open group?

**Comment by jefflembeck** [comment]
Absolutely!

**Comment by LetMyPeopleCode** [comment]
Woo Hoo. The restaurant in the readme is walking distance from my office. OOF last week of Sept for APIWorld.

**Comment by ghost** [comment]
I will show up for lunch or dinner any time that's not at the end of September! :tada:

**Comment by jefflembeck** [comment]
Early September is _likely_. Given the last two, that's pretty good spacing :smile:

**Comment by ghost** [comment]
in my excitement over DimSumJs, I forgot that I will be traveling in early September :confounded: . But I want to go one day :balloon: Also, @rmoshier, look what's happening!

**Comment by jonmadison** [comment]
😢

**Comment by jonmadison** [comment]
i should be here. FWIW Decibel is 9/23-9/27. Shouldn't affect much (I got my tickets, and am taking off to be available for all of it) but throwing it out there.

**Comment by LetMyPeopleCode** [comment]
I am currently available:
9/3, 9/4, 9/9, 9/11, 9/16, 9/18, 9/24

Please remember that 9/14 and 9/22-23 are the Jewish High Holidays this year and those dates would exclude any observant Jews. The other dates I'm not available are due to other commitments or they're on weekends.

**Comment by LetMyPeopleCode** [comment]
There's a Amazon Local deal for OAsian... 

http://local.amazon.com/seattle/B00M1U1ACY/dim-sum-lunch-or-dinner-at-oasian

**Comment by jefflembeck** [comment]
Ok, let's figure out a date out of that set up there.

9/9 works for me, anybody else?

/cc @jonmadison @rmoshier @skwak @KatieK2 @alexlande @marcysutton @shenoa @toddself

**Comment by KatieK2** [comment]
I'm going to pass this month. I'm just swamped right now. Y'all have fun! :D

**Comment by marcysutton** [comment]
I'm doing two talks that week, so I'll have to bow out. If it was the following week I'd be down.

**Comment by jefflembeck** [comment]
I'm good for the 16th as well, if that works better for folks.

**Comment by ghost** [comment]
I can do the 16th :100:

**Comment by toddself** [comment]
100% on the 16th as well!

**Comment by jonmadison** [comment]
same. i'm good

**Comment by jonmadison** [comment]
dang, coupon is sold out.

**Comment by jefflembeck** [comment]
Not TOO much of a worry there, only one per table and last time I think we
were like $2-3 more per person iirc.

**Comment by jefflembeck** [comment]
9/16 it is!

LET'S DO THIS

**Comment by shenoa** [comment]
I'm in! What time?

**Comment by LetMyPeopleCode** [comment]
9/16 is two days away. What's the official time and location?

**Comment by jonmadison** [comment]
o'asian right? 12-1:30? or 11:30-1?

**Comment by toddself** [comment]
I am happy with all of those  Noon would be best

**Comment by jonmadison** [comment]
i've been slotted to speak at work tomorrow during lunch, so i'm gonna have to skip out.

i guess the only consolation is that it's a talk on node.js

**Comment by ghost** [comment]
uuuugh, now I can't go anymore cuz I have to be at work orientation!
so not :100: after all

**Comment by toddself** [comment]
So that leaves Jeff and myself? Should we reschedule to next week?

**Comment by marcysutton** [comment]
I'm planning to be there. Next week would work too though.

**Comment by LetMyPeopleCode** [comment]
I'm planning to be there. That's 4.

**Comment by toddself** [comment]
oh great!  i had lost count of who was coming!

**Comment by LetMyPeopleCode** [comment]
And Alex Lande _swore_ he'd be at DimSumJS this time. He didn't swear by
Grabthar's hammer and the suns of Worvan, but I think he meant it.

**Comment by alexlande** [comment]
I did swear, and I swear I meant it, but I don't think I can swing it tomorrow. Sorry, y'all :(

**Comment by jefflembeck** [comment]
Make that 3. :(. Sorry y'all. In the middle of moving and need every minute
I can get where a 15 month old isn't getting into stuff.

**Comment by jonmadison** [comment]
congratulations jeff :)

**Comment by LetMyPeopleCode** [comment]
So now it's looking like Me, Todd, Shenoa, and Marcy. Any other people
coming (or not)?

**Comment by LetMyPeopleCode** [comment]
I've got a meeting at 1 that I'd love to get some more prep for, I think
I'm going to have to bow out for today.

**Comment by jonmadison** [comment]
sooo with the iOS9 release much of my team is focused on standing guard. :)
my lunch talk was canceled, so i'll have an hour available!

11:30, or noon?

**Comment by toddself** [comment]
sorry i'm out.  been up since who-knows-when with a sick 2 year old.

**Comment by marcysutton** [comment]
I think we should postpone until next week, since everyone is bailing 😄

**Comment by shenoa** [comment]
Makes sense! There's probably some minimum number of persons for a sensible dim sum meal. It's bound to be larger than two. 

Shenoa

**Comment by KatieK2** [comment]
+1 to NOT attempt dim-sum with a party of two. Enjoy, y'all! (I'm still out.)

**Comment by jonmadison** [comment]
Fine with me:)

(Confession: had dimsum yesterday)

**Comment by jefflembeck** [comment]
Ok, we super blew it on this one, let's reschedule for next month?
