### ISSUE TITLE
October

### ISSUE THREAD

**Issue by jefflembeck** [dimsumjs/Seattle#5]
We dropped the ball on September, but we can just eat more in October.

October 20th. noon. O'asian - Let's do this. Big time.

**Comment by jefflembeck** [comment]
On that note, let's stop figuring out dates and start just going with a set one, and then we know "Hey, I can make that next month" or something, because we have something steady and consistent.

**Comment by toddself** [comment]
I'm open any day except October 13-17!

**Comment by jefflembeck** [comment]
October 20th. Noon. O'asian

**Comment by ivanoats** [comment]
on my calendar :fork_and_knife:

**Comment by toddself** [comment]
in

**Comment by LetMyPeopleCode** [comment]
I'm in. On my calendar.

**Comment by jonmadison** [comment]
In

**Comment by skwak** [comment]
I'm in! Can do any day except Oct. 5-11

**Comment by katke** [comment]
Hooray!

**Comment by marcysutton** [comment]
And no bailing this time!

**Comment by LetMyPeopleCode** [comment]
You have my 100% iron-clad no-bail Guarantee*.

*In the event of an alien invasion, severe weather event, visit from the
president of China, my kid having kept me up until 5 a.m. due to virally or
bacterially caused bodily evacuations, my employer scheduling a last-minute
meeting, my workload getting out of hand, or the rapture, I reserve the
right to substitute my sincerest apologies for attendance.

**Comment by ghost** [comment]
ditto to the @YiddishNinja guarantee :smiling_imp:

**Comment by jonmadison** [comment]
👌🏾

**Comment by noahcollins** [comment]
I'm there. Such a good idea.

**Comment by Schoonology** [comment]
I'd hoping to make it down.

**Comment by LetMyPeopleCode** [comment]
Can I invite my manager?

**Comment by jefflembeck** [comment]
@YiddishNinja I think everybody is invited

**Comment by jefflembeck** [comment]
That being said, I just realized I have a doc appt during this :( so I'm out, again. Booo.

**Comment by toddself** [comment]
:ghost: jeff :(. 

So head count for tomorrow? I am in!

**Comment by LetMyPeopleCode** [comment]
I'm in.

**Comment by katke** [comment]
I'm planning on being there!

**Comment by Schoonology** [comment]
It looks like I'm not going to make it down. See y'all soon.

**Comment by LetMyPeopleCode** [comment]
I'm here in an orange shirt.

**Comment by toddself** [comment]
i am stuck on a bus in ballard.

seattle! :(

**Comment by ivanoats** [comment]
Looking for parking
