### ISSUE TITLE
December?

### ISSUE THREAD

**Issue by LetMyPeopleCode** [dimsumjs/Seattle#9]
I have some days open in December to get in a last one of the year. How's about y'all?

**Comment by jefflembeck** [comment]
Third Tuesday makes for 12/15 at Noon! O'asia!

Let's get this planned and going!

**Comment by LetMyPeopleCode** [comment]
Booked all through lunch time on the 15th and 17th next week. Sorry.

**Comment by KatieK2** [comment]
I'm in!

**Comment by toddself** [comment]
Yessssssss

**Comment by jefflembeck** [comment]
Today today today. Noon!

**Comment by KatieK2** [comment]
I'll be there!

**Comment by jefflembeck** [comment]
I know it's last minute, but anybody else?

@jonmadison
@ivanoats
@skwak
@katke 
@marcysutton
@noahcollins
@Schoonology
@shenoa

**Comment by ivanoats** [comment]
Thanks for the invite! I'm teaching until 12:30 today. Unfortunately wouldn't make it in time. Next time!

**Comment by noahcollins** [comment]
I won't make it to this one, but thanks for the invite.

**Comment by marcysutton** [comment]
I'm stuck in an internal all-day hackathon. Hopefully I can make the next one!

**Comment by ghost** [comment]
I can't make it, but I want to go next time! :calendar:
